# Import the necessary modules
from global_parameters_sampling import global_parameters_sampling
from local_parameters_tape_creator import local_parameters_tape_creator

# Run global_parameters_sampling
global_parameters_sampling()

# Run local_parameters_tape_creator
local_parameters_tape_creator()